pipeline {
    agent any

    environment {
        CI = "false" 
        VERCEL_TOKEN = "LR3pXpyR2FCj7tZ7kOcldVes"
    }

    tools {
        nodejs 'Node 20'
    }

    stages {
        stage('Clean workspace') {
            steps {
                // Limpia el directorio de trabajo completo.
                deleteDir()
            }
        }
        stage('Checkout') {
            steps {
                // Se utiliza la URL correcta de tu repositorio.
                git url: 'https://github.com/CamiloToroUCC/ProtectoFinalGameProyect.git', branch: 'main', credentialsId: 'github-token'
            }
        }
        stage('Install dependencies') {
            steps {
                // Cambia al directorio que contiene package.json
                dir('game-project') {
                    bat 'npm install --legacy-peer-deps'
                }
            }
        }
        stage('Run GameTracker Unit Tests') {
            steps {
                dir('game-project') {
                    bat 'npx vitest run src/Experience/__tests__/GameTracker.test.js'
                }
            }
        }
        stage('Build app') {
            steps {
                dir('game-project') {
                    bat 'npm run build'
                }
            }
        }
        stage('Deploy to Vercel') {
            steps {
                dir('game-project') {
                    // Se usa el flag --yes para confirmar el despliegue automáticamente.
                    bat 'npx vercel --prod --yes --token %VERCEL_TOKEN%'
                }
            }
        }
    }
}
